const fs = require('fs');
let c = fs.readFileSync('global-lang.js', 'utf8');

// The translations need to be FLAT keys, not nested, because t() does langData[key]
const bookingEn = {
  "booking.book_visit": "Book Your Visit",
  "booking.instant_confirm": "Instant Confirmation",
  "booking.mobile_tickets": "Mobile Tickets",
  "booking.free_cancel": "Free Cancellation",
  "booking.date_time": "Date & Time",
  "booking.tickets": "Tickets",
  "booking.addons": "Add-ons",
  "booking.checkout": "Checkout",
  "booking.select_date_time": "Select Date & Time",
  "booking.choose_date_time": "Choose your preferred visit date and time slot",
  "booking.available_slots": "Available Time Slots",
  "booking.morning": "Morning",
  "booking.late_morning": "Late Morning",
  "booking.afternoon": "Afternoon",
  "booking.late_afternoon": "Late Afternoon",
  "booking.sold_out": "Sold Out",
  "booking.select_tickets": "Select Tickets",
  "booking.choose_admission": "Choose your admission type and variations",
  "booking.international": "International",
  "booking.egyptian_arab": "Egyptian / Arab",
  "booking.general_admission": "General Admission",
  "booking.adult": "Adult",
  "booking.adult_desc": "Standard entry for visitors aged 12-60",
  "booking.student_child": "Student / Child",
  "booking.student_desc": "Ages 4-12 or Valid Student ID",
  "booking.guided_experience": "Guided Experience",
  "booking.guided_desc1": "Expert human guide + Includes General Admission",
  "booking.guided_desc2": "2-hour expert-led guided journey",
  "booking.ultimate_desc1": "The ultimate immersion + Immersive Gallery access",
  "booking.ultimate_desc2": "Full access to all museum areas",
  "booking.kids_museum": "Kids Museum",
  "booking.kids_desc1": "Interactive Zones, Junior Lab & Digital Sandpit",
  "booking.explorer_child": "Explorer (Child)",
  "booking.explorer_desc": "Ages 4-12. Full interactive access",
  "booking.guardian_adult": "Guardian (Adult)",
  "booking.guardian_desc": "Companion for kids museum only",
  "booking.enhance_visit": "Enhance Your Visit",
  "booking.enhance_desc": "Add extras to make your experience unforgettable",
  "booking.audio_guide": "Audio Guide",
  "booking.audio_desc": "Available in 8 languages. Expert narration.",
  "booking.ramses_exhibition": "Special Exhibition: Ramses II",
  "booking.ramses_desc": "Limited time access to the royal collection.",
  "booking.photo_pass": "Photography Pass",
  "booking.photo_desc": "Professional photography allowed in all halls.",
  "booking.vip_entry": "VIP Fast-Track Entry",
  "booking.vip_desc": "Skip the queue with priority access.",
  "booking.order_summary": "Order Summary",
  "booking.select_date": "Select a date",
  "booking.select_time": "Select a time",
  "booking.no_tickets": "No tickets selected yet",
  "booking.subtotal": "Subtotal",
  "booking.taxes": "Taxes & Fees (7%)",
  "booking.total": "Total",
  "booking.secure_payment": "Secure Payment",
  "booking.opening_hours": "Opening Hours",
  "booking.getting_here": "Getting Here",
  "booking.museum_rules": "Museum Rules",
  "booking.accessibility": "Accessibility",
  "booking.faq_1": "Can I reschedule my booking?",
  "booking.faq_2": "Are children under 6 allowed free entry?",
  "booking.faq_3": "Is parking available at the museum?",
  "booking.faq_4": "What payment methods are accepted?",
  "booking.add": "Add",
  "booking.online_booking": "Online Booking"
};

const bookingAr = {
  "booking.book_visit": "احجز زيارتك",
  "booking.instant_confirm": "تأكيد فوري",
  "booking.mobile_tickets": "تذاكر المحمول",
  "booking.free_cancel": "إلغاء مجاني",
  "booking.date_time": "التاريخ والوقت",
  "booking.tickets": "التذاكر",
  "booking.addons": "الإضافات",
  "booking.checkout": "الدفع",
  "booking.select_date_time": "اختر التاريخ والوقت",
  "booking.choose_date_time": "اختر تاريخ ووقت زيارتك المفضل",
  "booking.available_slots": "الأوقات المتاحة",
  "booking.morning": "صباحاً",
  "booking.late_morning": "قبل الظهر",
  "booking.afternoon": "بعد الظهر",
  "booking.late_afternoon": "عصراً",
  "booking.sold_out": "نفدت التذاكر",
  "booking.select_tickets": "اختر التذاكر",
  "booking.choose_admission": "اختر نوع الدخول الخاص بك",
  "booking.international": "دولي",
  "booking.egyptian_arab": "مصري / عربي",
  "booking.general_admission": "الدخول العام",
  "booking.adult": "بالغ",
  "booking.adult_desc": "دخول عادي للزوار من 12 إلى 60 عاماً",
  "booking.student_child": "طالب / طفل",
  "booking.student_desc": "الأعمار من 4-12 أو هوية طالب صالحة",
  "booking.guided_experience": "جولة إرشادية",
  "booking.guided_desc1": "مرشد بشري خبير + يشمل الدخول العام",
  "booking.guided_desc2": "جولة لمدة ساعتين بقيادة مرشد خبير",
  "booking.ultimate_desc1": "الاندماج التام + دخول معرض الانغماس",
  "booking.ultimate_desc2": "دخول كامل لجميع مناطق المتحف",
  "booking.kids_museum": "متحف الأطفال",
  "booking.kids_desc1": "مناطق تفاعلية، معمل صغير، وحوض رمل رقمي",
  "booking.explorer_child": "مستكشف (طفل)",
  "booking.explorer_desc": "الأعمار 4-12. دخول تفاعلي كامل",
  "booking.guardian_adult": "مرافق (بالغ)",
  "booking.guardian_desc": "مرافق لمتحف الأطفال فقط",
  "booking.enhance_visit": "عزز زيارتك",
  "booking.enhance_desc": "أضف إضافات لجعل تجربتك لا تُنسى",
  "booking.audio_guide": "دليل صوتي",
  "booking.audio_desc": "متوفر بـ 8 لغات. سرد خبير.",
  "booking.ramses_exhibition": "معرض خاص: رمسيس الثاني",
  "booking.ramses_desc": "وصول لفترة محدودة للمجموعة الملكية.",
  "booking.photo_pass": "تصريح تصوير",
  "booking.photo_desc": "يسمح بالتصوير الاحترافي في جميع القاعات.",
  "booking.vip_entry": "دخول VIP السريع",
  "booking.vip_desc": "تخطى الطابور مع الدخول ذو الأولوية.",
  "booking.order_summary": "ملخص الطلب",
  "booking.select_date": "اختر تاريخاً",
  "booking.select_time": "اختر وقتاً",
  "booking.no_tickets": "لم يتم اختيار تذاكر بعد",
  "booking.subtotal": "المجموع الفرعي",
  "booking.taxes": "الضرائب والرسوم (7%)",
  "booking.total": "الإجمالي",
  "booking.secure_payment": "دفع آمن",
  "booking.opening_hours": "ساعات العمل",
  "booking.getting_here": "كيفية الوصول",
  "booking.museum_rules": "قواعد المتحف",
  "booking.accessibility": "إمكانية الوصول",
  "booking.faq_1": "هل يمكنني إعادة جدولة حجزى؟",
  "booking.faq_2": "هل يُسمح للأطفال دون سن السادسة بالدخول مجانًا؟",
  "booking.faq_3": "هل يتوفر موقف للسيارات في المتحف؟",
  "booking.faq_4": "ما هي طرق الدفع المقبولة؟",
  "booking.add": "إضافة",
  "booking.online_booking": "حجز عبر الإنترنت"
};

// Inject as FLAT keys into en: { ... and ar: { ...
// The structure is: en: { "key": "value", ...
// We need to add our flat keys right after en: {
const enEntries = Object.entries(bookingEn).map(([k,v]) => `"${k}": "${v.replace(/"/g, '\\"')}"`).join(', ');
const arEntries = Object.entries(bookingAr).map(([k,v]) => `"${k}": "${v.replace(/"/g, '\\"')}"`).join(', ');

c = c.replace('en: {', 'en: { ' + enEntries + ',');
c = c.replace('ar: {', 'ar: { ' + arEntries + ',');

fs.writeFileSync('global-lang.js', c, 'utf8');
console.log('Injected flat booking keys into global-lang.js');
