document.addEventListener('DOMContentLoaded', () => {
     // ============================================
    // HIEROGLYPHIC TRANSLATION
    // ============================================
    const nameInput = document.getElementById('nameInput');
    const generateBtn = document.getElementById('generateBtn');
    const hieroglyphDisplay = document.getElementById('hieroglyphDisplay');
    const phoneticText = document.getElementById('phoneticText');

    const hieroglyphMap = {
        'a': '𓄿', 'b': '𓃀', 'c': '𓎡', 'd': '𓂧', 'e': '𓇋', 
        'f': '𓆑', 'g': '𓎼', 'h': '𓉔', 'i': '𓇋', 'j': '𓆓', 
        'k': '𓎡', 'l': '𓃭', 'm': '𓅓', 'n': '𓈖', 'o': '𓍯', 
        'p': '𓊪', 'q': '𓈎', 'r': '𓂋', 's': '𓋴', 't': '𓏏', 
        'u': '𓅱', 'v': '𓆑', 'w': '𓅱', 'x': '𓎡𓋴', 'y': '𓇋𓇋', 
        'z': '𓊃', ' ': ' '
    };

    generateBtn.addEventListener('click', async () => {
        const name = nameInput.value.trim();
        if (!name) { alert('Please enter a name to translate!'); return; }

        hieroglyphDisplay.style.opacity = '0';
        phoneticText.style.opacity = '0';
        generateBtn.innerHTML = '<span class="material-symbols-outlined animate-spin">sync</span> Carving...';
        generateBtn.disabled = true;

        const token = localStorage.getItem('token');
        if (!token) {
            alert('🔐 Authentication required. Please login to use this feature.');
            window.location.href = '../2.login/code.html';
            return;
        }

        try {
            const API_BASE_URL = (typeof window.API_BASE_URL !== 'undefined') ? window.API_BASE_URL : 'https://gem-backend-production-1ea2.up.railway.app/api';
            const response = await fetch(`${API_BASE_URL}/ai/name-to-cartouche`, {
                method: 'POST',
                headers: { 
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${token}`
                },
                body: JSON.stringify({ name })
            });

            if (!response.ok) throw new Error('Failed to generate cartouche');
            const data = await response.json();

            // Display image result
            hieroglyphDisplay.innerHTML = `<img src="${data.cartouche}" alt="${data.name} Cartouche" style="max-width:100%; height:auto; border-radius:10px;">`;
            phoneticText.textContent = data.name || name;

        } catch (error) {
            console.error('Error generating cartouche:', error);
            // Fallback to basic mapping if API fails
            let translated = '';
            for (let char of name.toLowerCase()) {
                translated += hieroglyphMap[char] ? hieroglyphMap[char] + ' ' : char + ' ';
            }
            hieroglyphDisplay.textContent = translated.trim();
            phoneticText.textContent = name;
        } finally {
            hieroglyphDisplay.style.opacity = '1';
            phoneticText.style.opacity = '1';
            generateBtn.innerHTML = 'Generate Inscription';
            generateBtn.disabled = false;
        }
    });

    nameInput.addEventListener('keypress', e => {
        if (e.key === 'Enter') generateBtn.click();
    });

    hieroglyphDisplay.style.transition = 'opacity 300ms ease';
    phoneticText.style.transition = 'opacity 300ms ease';

    // ============================================
    // DOWNLOAD BUTTON
    // ============================================
    const downloadBtn = document.getElementById('downloadBtn');
    downloadBtn.addEventListener('click', () => {
        const hieroglyphText = hieroglyphDisplay.textContent;
        const phoneticTextValue = phoneticText.textContent;
        if (!hieroglyphText || hieroglyphText === '𓀀 𓃠 𓅓 𓏏') { alert('Please generate an inscription first!'); return; }

        const content = `PHARAOH LAB - INSCRIPTION\n\n${hieroglyphText}\n\nPhonetic: ${phoneticTextValue}\n\nGenerated by The Eternal Curator`;
        const blob = new Blob([content], { type: 'text/plain' });
        const a = document.createElement('a');
        a.href = window.URL.createObjectURL(blob);
        a.download = 'inscription.txt';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
    });

    // ============================================
    // SHARE BUTTON
    // ============================================
    const shareBtn = document.getElementById('shareBtn');
    shareBtn.addEventListener('click', () => {
        const hieroglyphText = hieroglyphDisplay.textContent;
        const phoneticTextValue = phoneticText.textContent;
        if (!hieroglyphText || hieroglyphText === '𓀀 𓃠 𓅓 𓏏') { alert('Please generate an inscription first!'); return; }

        const shareText = `Check out my hieroglyphic inscription from PHARAOH LAB:\n${hieroglyphText}\n(${phoneticTextValue})`;

        if (navigator.share) {
            navigator.share({ title: 'PHARAOH LAB Inscription', text: shareText }).catch(err => console.log('Share failed:', err));
        } else {
            navigator.clipboard.writeText(shareText).then(() => alert('Inscription copied to clipboard!')).catch(() => alert('Share not supported on this device'));
        }
    });

    // ============================================
    // ACCOUNT BUTTON
    // ============================================
    const accountBtn = document.getElementById('accountBtn');
    if(accountBtn) {
        accountBtn.addEventListener('click', () => {
            alert('Account feature coming soon!');
        });
    }

    // ============================================
    // SCROLL TO TOP BUTTON
    // ============================================
    const scrollTopBtn = document.getElementById('scrollTopBtn');
    if(scrollTopBtn) {
        window.addEventListener('scroll', () => {
            if(window.scrollY > 300) {
                scrollTopBtn.style.opacity = '1';
                scrollTopBtn.style.pointerEvents = 'auto';
            } else {
                scrollTopBtn.style.opacity = '0';
                scrollTopBtn.style.pointerEvents = 'none';
            }
        });

        scrollTopBtn.addEventListener('click', () => {
            window.scrollTo({ top: 0, behavior: 'smooth' });
        });

        scrollTopBtn.style.transition = 'opacity 300ms ease';
        scrollTopBtn.style.opacity = '0';
        scrollTopBtn.style.pointerEvents = 'none';
    }
});

