document.addEventListener('DOMContentLoaded', () => {
     // ============================================
    // HIEROGLYPHIC TRANSLATION
    // ============================================
    const nameInput = document.getElementById('nameInput');
    const generateBtn = document.getElementById('generateBtn');
    const hieroglyphDisplay = document.getElementById('hieroglyphDisplay');
    const phoneticText = document.getElementById('phoneticText');

    generateBtn.addEventListener('click', async () => {
        const name = nameInput.value.trim();
        if (!name) { alert('Please enter a name to translate!'); return; }

        const token = localStorage.getItem('token');
        if (!token) {
            alert('🔐 Authentication required. Please login to use the Royal Cartouche generator.');
            window.location.href = '../2.login/code.html';
            return;
        }

        hieroglyphDisplay.style.opacity = '0';
        phoneticText.style.opacity = '0';
        generateBtn.innerHTML = '<span class="material-symbols-outlined animate-spin">sync</span> Carving...';
        generateBtn.disabled = true;

        try {
            const response = await fetch('https://gem-backend-production-1ea2.up.railway.app/api/ai/name-to-cartouche', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${token}`
                },
                body: JSON.stringify({ name })
            });

            let data = {};
            try {
                data = await response.json();
            } catch (jsonError) {
                console.error('Failed to parse JSON from server response:', jsonError);
            }

            if (response.ok && data.cartouche) {
                let imgSrc = data.cartouche;
                if (!imgSrc.startsWith('http') && !imgSrc.startsWith('data:')) {
                    imgSrc = `data:image/png;base64,${imgSrc}`;
                }
                hieroglyphDisplay.innerHTML = `<img src="${imgSrc}" alt="Cartouche" style="max-height: 120px; border-radius: 8px;">`;
                phoneticText.textContent = data.name || name;
            } else if (response.status === 401 || response.status === 403) {
                alert('🔐 Session expired. Please sign in again.');
                localStorage.removeItem('token');
                window.location.href = '../2.login/code.html';
            } else {
                alert(`⚠️ Translation failed: ${data.message || 'The gods are busy, please try again later.'}`);
            }
        } catch (error) {
            console.error('API Translation Error:', error);
            alert('⚠️ Network connection failed. The ritual was interrupted.');
        } finally {
            hieroglyphDisplay.style.opacity = '1';
            phoneticText.style.opacity = '1';
            generateBtn.innerHTML = 'Generate Inscription';
            generateBtn.disabled = false;
        }
    });

    nameInput.addEventListener('keypress', e => {
        if (e.key === 'Enter') generateBtn.click();
    });

    hieroglyphDisplay.style.transition = 'opacity 300ms ease';
    phoneticText.style.transition = 'opacity 300ms ease';

    // ============================================
    // DOWNLOAD BUTTON
    // ============================================
    const downloadBtn = document.getElementById('downloadBtn');
    downloadBtn.addEventListener('click', () => {
        const hieroglyphText = hieroglyphDisplay.textContent;
        const phoneticTextValue = phoneticText.textContent;
        if (!hieroglyphText || hieroglyphText === '𓀀 𓃠 𓅓 𓏏') { alert('Please generate an inscription first!'); return; }

        const content = `PHARAOH LAB - INSCRIPTION\n\n${hieroglyphText}\n\nPhonetic: ${phoneticTextValue}\n\nGenerated by The Eternal Curator`;
        const blob = new Blob([content], { type: 'text/plain' });
        const a = document.createElement('a');
        a.href = window.URL.createObjectURL(blob);
        a.download = 'inscription.txt';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
    });

    // ============================================
    // SHARE BUTTON
    // ============================================
    const shareBtn = document.getElementById('shareBtn');
    shareBtn.addEventListener('click', () => {
        const hieroglyphText = hieroglyphDisplay.textContent;
        const phoneticTextValue = phoneticText.textContent;
        if (!hieroglyphText || hieroglyphText === '𓀀 𓃠 𓅓 𓏏') { alert('Please generate an inscription first!'); return; }

        const shareText = `Check out my hieroglyphic inscription from PHARAOH LAB:\n${hieroglyphText}\n(${phoneticTextValue})`;

        if (navigator.share) {
            navigator.share({ title: 'PHARAOH LAB Inscription', text: shareText }).catch(err => console.log('Share failed:', err));
        } else {
            navigator.clipboard.writeText(shareText).then(() => alert('Inscription copied to clipboard!')).catch(() => alert('Share not supported on this device'));
        }
    });

    // ============================================
    // ACCOUNT BUTTON
    // ============================================
    const accountBtn = document.getElementById('accountBtn');
    if(accountBtn) {
        accountBtn.addEventListener('click', () => {
            alert('Account feature coming soon!');
        });
    }

    // ============================================
    // SCROLL TO TOP BUTTON
    // ============================================
    const scrollTopBtn = document.getElementById('scrollTopBtn');
    if(scrollTopBtn) {
        window.addEventListener('scroll', () => {
            if(window.scrollY > 300) {
                scrollTopBtn.style.opacity = '1';
                scrollTopBtn.style.pointerEvents = 'auto';
            } else {
                scrollTopBtn.style.opacity = '0';
                scrollTopBtn.style.pointerEvents = 'none';
            }
        });

        scrollTopBtn.addEventListener('click', () => {
            window.scrollTo({ top: 0, behavior: 'smooth' });
        });

        scrollTopBtn.style.transition = 'opacity 300ms ease';
        scrollTopBtn.style.opacity = '0';
        scrollTopBtn.style.pointerEvents = 'none';
    }
});

