import React, { useState } from 'react';
import '../styles/AI-common.css';
import '../styles/NameTranslator.css';

const NameTranslatorPage = () => {
    const API_URL = 'https://gem-backend-production-cb6d.up.railway.app/api';
    const [name, setName] = useState('');
    const [hieroglyphDisplay, setHieroglyphDisplay] = useState('𓀀 𓃠 𓅓 𓏏');
    const [phoneticText, setPhoneticText] = useState('Amun-Ra-Te');
    const [isGenerating, setIsGenerating] = useState(false);

    const hieroglyphMap = {
        'a': '𓀀', 'b': '𓀁', 'c': '𓀂', 'd': '𓀃', 'e': '𓀄',
        'f': '𓀅', 'g': '𓀆', 'h': '𓀇', 'i': '𓀈', 'j': '𓀉',
        'k': '𓀊', 'l': '𓀋', 'm': '𓀌', 'n': '𓀍', 'o': '𓀎',
        'p': '𓀏', 'q': '𓀐', 'r': '𓀑', 's': '𓀒', 't': '𓀓',
        'u': '𓀔', 'v': '𓀕', 'w': '𓀖', 'x': '𓀗', 'y': '𓀘',
        'z': '𓀙'
    };

    const phoneticMap = {
        'a': 'A', 'b': 'B', 'c': 'K', 'd': 'D', 'e': 'E',
        'f': 'F', 'g': 'G', 'h': 'H', 'i': 'I', 'j': 'J',
        'k': 'K', 'l': 'L', 'm': 'M', 'n': 'N', 'o': 'O',
        'p': 'P', 'q': 'Q', 'r': 'R', 's': 'S', 't': 'T',
        'u': 'U', 'v': 'V', 'w': 'W', 'x': 'X', 'y': 'Y',
        'z': 'Z'
    };

    const translateToHieroglyphicsLocal = (text) => {
        const cleanText = text.toLowerCase().replace(/[^a-z]/g, '');
        let hieroglyphics = '';
        let phonetic = '';

        for (let char of cleanText) {
            if (hieroglyphMap[char]) {
                hieroglyphics += hieroglyphMap[char] + ' ';
                phonetic += phoneticMap[char] + '-';
            }
        }

        return {
            hieroglyphics: hieroglyphics.trim(),
            phonetic: phonetic.slice(0, -1)
        };
    };

    const handleGenerate = async () => {
        const trimmedName = name.trim();
        if (!trimmedName) { 
            alert('Please enter a name to translate!'); 
            return; 
        }

        const token = localStorage.getItem('token');
        if (!token) {
            alert('🔐 Authentication required. Please login to use the Royal Cartouche generator.');
            window.location.href = '/login';
            return;
        }

        setIsGenerating(true);

        try {
            const response = await fetch(`${API_URL}/ai/name-to-cartouche`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${token}`
                },
                body: JSON.stringify({ name: trimmedName })
            });

            const data = await response.json();

            if (response.ok && (data.hieroglyphics || data.cartouche)) {
                setHieroglyphDisplay(data.hieroglyphics || data.cartouche);
                setPhoneticText(data.phonetic || trimmedName);
            } else if (response.status === 401 || response.status === 403) {
                alert('🔐 Session expired. Please sign in again.');
                localStorage.removeItem('token');
                window.location.href = '/login';
            } else {
                console.warn('API Error, falling back to local translation:', data.message);
                const localGen = translateToHieroglyphicsLocal(trimmedName);
                setHieroglyphDisplay(localGen.hieroglyphics);
                setPhoneticText(localGen.phonetic);
            }
        } catch (error) {
            console.error('API Translation Error, failing back to local:', error);
            const { hieroglyphics, phonetic } = translateToHieroglyphicsLocal(trimmedName);
            setHieroglyphDisplay(hieroglyphics);
            setPhoneticText(phonetic || trimmedName);
        } finally {
            setIsGenerating(false);
        }
    };

    const handleKeyDown = (e) => {
        if (e.key === 'Enter') handleGenerate();
    };

    const handleDownload = () => {
        if (!hieroglyphDisplay || hieroglyphDisplay === '𓀀 𓃠 𓅓 𓏏') { 
            alert('Please generate an inscription first!'); 
            return; 
        }
        const content = `PHARAOH LAB - INSCRIPTION\n\n${hieroglyphDisplay}\n\nPhonetic: ${phoneticText}\n\nGenerated by The Eternal Curator`;
        const blob = new Blob([content], { type: 'text/plain' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'inscription.txt';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);
    };

    const handleShare = () => {
        if (!hieroglyphDisplay || hieroglyphDisplay === '𓀀 𓃠 𓅓 𓏏') { 
            alert('Please generate an inscription first!'); 
            return; 
        }

        const shareText = `Check out my hieroglyphic inscription from PHARAOH LAB:\n${hieroglyphDisplay}\n(${phoneticText})`;

        if (navigator.share) {
            navigator.share({ title: 'PHARAOH LAB Inscription', text: shareText }).catch(err => console.log('Share failed:', err));
        } else {
            navigator.clipboard.writeText(shareText)
                .then(() => alert('Inscription copied to clipboard!'))
                .catch(() => alert('Share not supported on this device'));
        }
    };

    return (
        <div className="ai-page-container">
            <main className="ai-container">
                {/* Background Decorations */}
                <div className="background-decoration decoration-1"></div>
                <div className="background-decoration decoration-2"></div>

                {/* Hero Section */}
                <div className="hero-section">
                    <div className="hero-container">
                        {/* Header */}
                        <div className="hero-header">
                            <span className="hero-label">Ancient Scriptorium</span>
                            <h1 className="ai-display-font hero-title ai-gold-text">Inscribe Your Name</h1>
                            <p className="hero-description">
                                Translate your modern identity into the sacred symbols of the Old Kingdom. Every character is a vessel of eternal spirit.
                            </p>
                        </div>

                    {/* Main Card */}
                    <div className="main-card">
                        {/* Golden Corner Accents */}
                        <div className="corner-accent corner-top-left"></div>
                        <div className="corner-accent corner-top-right"></div>
                        <div className="corner-accent corner-bottom-left"></div>
                        <div className="corner-accent corner-bottom-right"></div>

                        <div className="card-content">
                            {/* Input Section */}
                            <div className="input-section">
                                <div className="input-group">
                                    <label className="input-label">The Subject Name</label>
                                    <input 
                                        type="text" 
                                        className="input-field" 
                                        id="nameInput" 
                                        placeholder="Enter your name..."
                                        value={name}
                                        onChange={(e) => setName(e.target.value)}
                                        onKeyDown={handleKeyDown}
                                        disabled={isGenerating}
                                    />
                                </div>

                                <div className="options-group">
                                    <div className="radio-option">
                                        <input type="radio" id="cartoucheStyle" name="style" defaultChecked />
                                        <label htmlFor="cartoucheStyle" className="radio-label">Royal Cartouche Style</label>
                                    </div>
                                    <div className="radio-option disabled">
                                        <input type="radio" id="demoticScript" name="style" disabled />
                                        <label htmlFor="demoticScript" className="radio-label">Demotic Script</label>
                                    </div>
                                </div>

                                <button 
                                    className="generate-btn" 
                                    id="generateBtn"
                                    onClick={handleGenerate}
                                    disabled={isGenerating}
                                >
                                    {isGenerating ? (
                                        <><span className="material-symbols-outlined animate-spin">sync</span> Carving...</>
                                    ) : (
                                        'Generate Inscription'
                                    )}
                                </button>
                            </div>

                            {/* Display Section */}
                            <div className="display-section">
                                <div className="artifact-ref">Artifact Ref: #4092-A</div>
                                <div 
                                    className="hieroglyph-display" 
                                    id="hieroglyphDisplay"
                                    style={{ opacity: isGenerating ? 0 : 1 }}
                                >
                                    {hieroglyphDisplay}
                                </div>
                                <div className="phonetic-section">
                                    <div className="divider"></div>
                                    <p className="phonetic-label">Phonetic Rendering</p>
                                    <p 
                                        className="phonetic-text" 
                                        id="phoneticText"
                                        style={{ opacity: isGenerating ? 0 : 1 }}
                                    >
                                        {phoneticText}
                                    </p>
                                </div>
                                <div className="action-buttons">
                                    <button className="action-btn" id="downloadBtn" onClick={handleDownload}>
                                        <span className="material-symbols-outlined">download</span>
                                    </button>
                                    <button className="action-btn" id="shareBtn" onClick={handleShare}>
                                        <span className="material-symbols-outlined">share</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Footer Context */}
                    <div className="footer-context">
                        <div className="context-info">
                            <span className="material-symbols-outlined">info</span>
                            <p>Translation based on Middle Kingdom grammar conventions.</p>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
    );
};

export default NameTranslatorPage;
