const HALLS_DATA = [
    {
        "id": "6643b109558a239478145f07",
        "title": "Tutankhamun's Mask",
        "dynasty": "18th Dynasty",
        "material": "Solid Gold & Lapis Lazuli",
        "site": "Unknown",
        "gallery": "Tutankhamun Galleries",
        "description": "This world-famous funerary mask is crafted from two layers of high-karat gold, inlaid with lapis lazuli, carnelian, and turquoise. It was designed to protect the king's spirit (Ka) and ensure his recognition in the afterlife, weighing over 10 kilograms of solid gold.",
        "date": "",
        "image": "../Halls Gallery/images/tut.png"
    },
    {
        "id": "6643b109558a239478145f08",
        "title": "Golden Throne",
        "dynasty": "18th Dynasty",
        "material": "Gold-covered Wood",
        "site": "Unknown",
        "gallery": "Tutankhamun Galleries",
        "description": "A masterpiece of Amarna-style art, this wooden throne is encased in gold leaf and decorated with silver, glass, and semi-precious stones. The backrest depicts an intimate scene of Queen Ankhesenamun anointing King Tutankhamun under the life-giving rays of the Aten.",
        "date": "",
        "image": "../Halls Gallery/images/golden_throne.png"
    },
    {
        "id": "6643b109558a239478145f09",
        "title": "Ceremonial Chariot",
        "dynasty": "18th Dynasty",
        "material": "Gilded Wood & Leather",
        "site": "Unknown",
        "gallery": "Tutankhamun Galleries",
        "description": "One of the six chariots found in the tomb's antechamber, this state chariot is light, fast, and covered in gold foil. Its intricate decorations show the Pharaoh as a warrior-king, crushing Egypt's enemies under his wheels in a display of divine power.",
        "date": "",
        "image": "../Halls Gallery/images/ceremonial_chariot.png"
    },
    {
        "id": "6643b109558a239478145f0a",
        "title": "Golden Fan (Flabellum)",
        "dynasty": "18th Dynasty",
        "material": "Gilded Wood",
        "site": "Unknown",
        "gallery": "Tutankhamun Galleries",
        "description": "A semi-circular fan found in the burial chamber, once held 42 ostrich feathers. The scenes on the gold foil show the king hunting ostriches in the desert to provide feathers for this very fan.",
        "date": "",
        "image": "../Halls Gallery/images/golden_fan.png"
    },
    {
        "id": "6643b109558a239478145f0b",
        "title": "Colossal Ramses II",
        "dynasty": "19th Dynasty",
        "material": "Red Granite",
        "site": "Unknown",
        "gallery": "Grand Hall",
        "description": "Standing 11 meters tall and weighing 82 tons, this red granite giant was discovered in Memphis. It now stands in the Great Atrium of the GEM, precisely oriented so that the sun illuminates the king's face twice a year during the solar alignment event.",
        "date": "",
        "image": "../Halls Gallery/images/grand.png"
    },
    {
        "id": "merneptah-stele",
        "title": "Victory Stele of Merneptah",
        "dynasty": "19th Dynasty",
        "material": "Black Granite",
        "site": "Unknown",
        "gallery": "Grand Hall",
        "description": "Also known as the Israel Stele, this massive black granite slab commemorates King Merneptah's military victories. It is famous for containing the earliest known historical mention of 'Israel' in an ancient text.",
        "date": "",
        "image": "../Halls Gallery/images/Victory Stele of Merneptah.png"
    },
    {
        "id": "senusret-statue",
        "title": "Statue of Senusret I",
        "dynasty": "12th Dynasty",
        "material": "Limestone",
        "site": "Unknown",
        "gallery": "Grand Hall",
        "description": "A beautifully preserved seated colossus of the Middle Kingdom pharaoh Senusret I. It showcases the refined artistic style of the 12th Dynasty, emphasizing the king's divine authority and serene majesty.",
        "date": "",
        "image": "../Halls Gallery/images/Statue of Senusret I.png"
    },
    {
        "id": "6643b109558a239478145f0c",
        "title": "Granite Column of Merneptah",
        "dynasty": "19th Dynasty",
        "material": "Red Granite",
        "site": "Unknown",
        "gallery": "Grand Hall",
        "description": "This 5.6-meter-high monolithic red granite column originally stood in the temple of Ptah at Memphis. It is inscribed with the titles of Ramses II's son, King Merneptah, celebrating his military victories and divine favor.",
        "date": "",
        "image": "../Halls Gallery/images/column_merneptah.png"
    },
    {
        "id": "6643b109558a239478145f0d",
        "title": "Colossus of a Ptolemaic King",
        "dynasty": "Ptolemaic Period",
        "material": "Red Granite",
        "site": "Unknown",
        "gallery": "Grand Hall",
        "description": "Recovered from the waters of Alexandria, this massive red granite statue represents a Ptolemaic ruler dressed as a traditional Egyptian Pharaoh, bridging the gap between Hellenistic leadership and ancient Egyptian tradition.",
        "date": "",
        "image": "../Halls Gallery/images/ptolemaic_king.png"
    },
    {
        "id": "6643b109558a239478145f0e",
        "title": "Colossus of a Ptolemaic Queen",
        "dynasty": "Ptolemaic Period",
        "material": "Dark Granite",
        "site": "Unknown",
        "gallery": "Grand Hall",
        "description": "Carved with exceptional detail in dark granite, this statue represents a queen of the Ptolemaic dynasty. The queen holds a double cornucopia, a Greek symbol of fertility and abundance, while wearing a traditional Egyptian tripartite wig.",
        "date": "",
        "image": "../Halls Gallery/images/ptolemaic_queen.png"
    },
    {
        "id": "6643b109558a239478145f10",
        "title": "Sarcophagus of Seti I",
        "dynasty": "19th Dynasty",
        "material": "Alabaster",
        "site": "Unknown",
        "gallery": "Royal Mummies Hall",
        "description": "Carved from a single block of translucent alabaster, this sarcophagus is a masterpiece of New Kingdom art. Its interior and exterior are covered in delicate hieroglyphic inscriptions and scenes from the 'Book of Gates', once inlaid with blue copper-sulfate.",
        "date": "",
        "image": "../Halls Gallery/images/sarcophagus_seti.png"
    },
    {
        "id": "6643b109558a239478145f11",
        "title": "Canopic Chest of Queen Hetepheres",
        "dynasty": "4th Dynasty",
        "material": "Calcite",
        "site": "Unknown",
        "gallery": "Royal Mummies Hall",
        "description": "Found in a secret shaft near the Great Pyramid, this calcite (alabaster) chest is one of the oldest and most important funerary objects known. It contains four compartments that once held the viscera of the queen, protected by the divine will.",
        "date": "",
        "image": "../Halls Gallery/images/canopic_chest_hetepheres.png"
    },
    {
        "id": "6643b109558a239478145f12",
        "title": "Golden Mask of Psusennes I",
        "dynasty": "21st Dynasty",
        "material": "Solid Gold",
        "site": "Unknown",
        "gallery": "Royal Mummies Hall",
        "description": "A stunning rival to Tutankhamun's treasure, this solid gold mask from the 'Silver Pharaoh' was found in the royal necropolis at Tanis. It reflects the resilience and craftsmanship of the Third Intermediate Period, symbolizing the king's eternal divine nature.",
        "date": "",
        "image": "../Halls Gallery/images/mask_psusennes.png"
    },
    {
        "id": "6643b109558a239478145f13",
        "title": "Senet Game Board",
        "dynasty": "New Kingdom",
        "material": "Ivory & Ebony",
        "site": "Unknown",
        "gallery": "Daily Life Hall",
        "description": "Senet was the most popular strategy game in ancient Egypt. This ivory-inlaid box served both as a game for leisure and a symbolic ritual representing the journey of the Ba (soul) through the trials of the underworld to reach eternal peace.",
        "date": "",
        "image": "../Halls Gallery/images/senet_board.png"
    },
    {
        "id": "6643b109558a239478145f14",
        "title": "Scribe's Palette and Pens",
        "dynasty": "Middle Kingdom",
        "material": "Wood",
        "site": "Unknown",
        "gallery": "Daily Life Hall",
        "description": "The hallmark of the intellectual class, this wooden palette contains depressions for black (carbon) and red (ochre) ink. It belonged to a scribe who played a vital role in the administration, tax collection, and religious documentation of the state.",
        "date": "",
        "image": "../Halls Gallery/images/scribe_palette.png"
    },
    {
        "id": "6643b109558a239478145f15",
        "title": "Cosmetic Palette",
        "dynasty": "Predynastic",
        "material": "Siltstone",
        "site": "Unknown",
        "gallery": "Daily Life Hall",
        "description": "Even before the Pharaohs, Egyptians valued beauty and ritual. This siltstone palette was used to grind green malachite or black galena into eye paint, which served both as protection against the desert sun and as a spiritual ward against evil.",
        "date": "",
        "image": "../Halls Gallery/images/cosmetic_palette.png"
    },
    {
        "id": "6643b109558a239478145f16",
        "title": "Ancient Egyptian Sandals",
        "dynasty": "New Kingdom",
        "material": "Papyrus & Palm Leaf",
        "site": "Unknown",
        "gallery": "Daily Life Hall",
        "description": "Woven with incredible precision from papyrus fibers and palm leaves, these sandals offer a glimpse into the sophisticated fashion of the New Kingdom. Such items were often buried with their owners to ensure comfort in the afterlife.",
        "date": "",
        "image": "../Halls Gallery/images/ancient_sandals.png"
    },
    {
        "id": "6643b109558a239478145f17",
        "title": "Royal Makeup Kit",
        "dynasty": "Middle Kingdom",
        "material": "Cedar wood, Ivory & Copper",
        "site": "Unknown",
        "gallery": "Daily Life Hall",
        "description": "A luxury vanity box containing bronze mirrors, obsidian jars for oils, and copper applicators for eye paint. It belonged to a noblewoman, showcasing the high standards of hygiene and beauty in the Middle Kingdom.",
        "date": "",
        "image": "../Halls Gallery/images/makeup_kit.png"
    },
    {
        "id": "6643b109558a239478145f18",
        "title": "The Seated Scribe",
        "dynasty": "5th Dynasty",
        "material": "Painted Limestone",
        "site": "Unknown",
        "gallery": "Sculpture & Statues Hall",
        "description": "Unearthed at Saqqara, this painted limestone statue is legendary for its realism. Unlike the idealized statues of Pharaohs, the scribe is shown with a soft physique, high cheekbones, and attentive rock-crystal eyes, eternally prepared to record the words of the gods.",
        "date": "",
        "image": "../Halls Gallery/images/seated_scribe.png"
    },
    {
        "id": "6643b109558a239478145f19",
        "title": "Statue of King Khafre",
        "dynasty": "4th Dynasty",
        "material": "Diorite",
        "site": "Unknown",
        "gallery": "Sculpture & Statues Hall",
        "description": "Carved from extremely hard dark diorite, this statue depicts the builder of the second pyramid at Giza. The king sits on a throne flanked by lions, while the falcon god Horus perches behind his head, spreading his wings in a gesture of divine protection and unity.",
        "date": "",
        "image": "../Halls Gallery/images/khafre_statue.png"
    },
    {
        "id": "6643b109558a239478145f1a",
        "title": "Group Statue of Menkaure",
        "dynasty": "4th Dynasty",
        "material": "Greywacke",
        "site": "Unknown",
        "gallery": "Sculpture & Statues Hall",
        "description": "This greywacke triad shows King Menkaure standing between the goddess Hathor and a personification of an Egyptian province (nome). It exemplifies the perfection of Old Kingdom artistic proportions and the intimate relationship between the monarch and the divine.",
        "date": "",
        "image": "../Halls Gallery/images/menkaure_statue.png"
    },
    {
        "id": "6643b109558a239478145f1b",
        "title": "Bust of Nefertiti (Replica)",
        "dynasty": "Amarna Period",
        "material": "Painted Limestone",
        "site": "Unknown",
        "gallery": "Sculpture & Statues Hall",
        "description": "This world-renowned bust captures the 'Great Royal Wife' of the heretic king Akhenaten. Known for its graceful neck and perfect symmetry, the original was found in the workshop of the sculptor Thutmose, serving as a model for royal portraiture during the Amarna revolution.",
        "date": "",
        "image": "../Halls Gallery/images/nefertiti_bust.png"
    },
    {
        "id": "6643b109558a239478145f1c",
        "title": "Statue of King Djoser",
        "dynasty": "3rd Dynasty",
        "material": "Limestone",
        "site": "Unknown",
        "gallery": "Sculpture & Statues Hall",
        "description": "The oldest life-size Egyptian statue known, found in a small chamber (Serdab) next to the Step Pyramid. The king's eyes are focused upward, looking toward the eternal stars through two small holes in the chamber wall.",
        "date": "",
        "image": "../Halls Gallery/images/djoser_statue.png"
    },
    {
        "id": "6643b109558a239478145f1d",
        "title": "Narmer Palette (Replica)",
        "dynasty": "Protodynastic",
        "material": "Siltstone",
        "site": "Unknown",
        "gallery": "Pre-Dynastic Period Hall",
        "description": "Considered the first historical document in the world, this palette commemorates the unification of Upper and Lower Egypt under King Narmer. It establishes the artistic conventions—such as hierarchical scale and registers—that would define Egyptian art for the next 3,000 years.",
        "date": "",
        "image": "../Halls Gallery/images/narmer_palette.png"
    },
    {
        "id": "6643b109558a239478145f1e",
        "title": "Painted Predynastic Vessel",
        "dynasty": "Naqada II",
        "material": "Pottery (Clay)",
        "site": "Unknown",
        "gallery": "Pre-Dynastic Period Hall",
        "description": "This Gerzean pottery vessel is decorated with ochre-red paint depicting multi-oared boats, mountain ranges, and flamingos. It illustrates the importance of the Nile as a highway for trade and communication even before the dawn of the Pharaonic state.",
        "date": "",
        "image": "../Halls Gallery/images/predynastic_vessel.png"
    },
    {
        "id": "6643b109558a239478145f1f",
        "title": "Ritual Flint Knife",
        "dynasty": "Predynastic",
        "material": "Flint & Ivory",
        "site": "Unknown",
        "gallery": "Pre-Dynastic Period Hall",
        "description": "Known as the Gebel el-Arak knife style, this object features a ripple-flaked flint blade of incredible sharpness. The ivory handle is carved with microscopic detail, showing complex battle scenes and mythological motifs, reflecting early Mesopotamian influence.",
        "date": "",
        "image": "../Halls Gallery/images/flint_knife.png"
    },
    {
        "id": "6643b109558a239478145f20",
        "title": "Terra-cotta Female Figure",
        "dynasty": "Naqada I",
        "material": "Terra-cotta",
        "site": "Unknown",
        "gallery": "Pre-Dynastic Period Hall",
        "description": "A stylized female figure with upraised arms, likely representing a dancer or a goddess. This early form of sculptural expression showcases the beginning of the spiritual and artistic journey of the Nile Valley inhabitants.",
        "date": "",
        "image": "../Halls Gallery/images/terracotta_figure.png"
    },
    {
        "id": "6643b109558a239478145f21",
        "title": "Anubis Guardian Statue",
        "dynasty": "New Kingdom",
        "material": "Gilded Wood & Resin",
        "site": "Unknown",
        "gallery": "Beliefs in the Afterlife",
        "description": "This recumbent jackal represents the god of mummification and the protector of tombs. Carved from wood and covered in black resin, Anubis was the 'Lord of the Sacred Land' who guided the deceased through the hall of Maat to their final judgment.",
        "date": "",
        "image": "../Halls Gallery/images/anubis_guardian.png"
    },
    {
        "id": "6643b109558a239478145f22",
        "title": "Book of the Dead Fragment",
        "dynasty": "New Kingdom",
        "material": "Papyrus",
        "site": "Unknown",
        "gallery": "Beliefs in the Afterlife",
        "description": "This papyrus scroll fragment is a personalized collection of hymns, spells, and instructions to help the deceased navigate the dangers of the Duat (underworld). It includes the critical 'negative confession' needed to pass the weighing of the heart.",
        "date": "",
        "image": "../Halls Gallery/images/book_of_dead.png"
    },
    {
        "id": "6643b109558a239478145f23",
        "title": "Shabti Figures of Tutankhamun",
        "dynasty": "18th Dynasty",
        "material": "Blue Faience",
        "site": "Unknown",
        "gallery": "Beliefs in the Afterlife",
        "description": "These blue faience figurines were magical workers for the afterlife. Each is inscribed with a spell from the Book of the Dead, ensuring that if the king were called upon to perform any manual labor in the next world, the shabti would stand and say, 'Here I am!'",
        "date": "",
        "image": "../Halls Gallery/images/tut_shabti.png"
    },
    {
        "id": "6643b109558a239478145f24",
        "title": "Gilded Mummy Mask",
        "dynasty": "Late Period",
        "material": "Cartonnage & Gold Leaf",
        "site": "Unknown",
        "gallery": "Beliefs in the Afterlife",
        "description": "A stunning mask made of cartonnage (layers of linen and plaster) and covered in gold leaf. It served to preserve the features of the deceased and provide them with a divine, incorruptible face for eternity.",
        "date": "",
        "image": "../Halls Gallery/images/mummy_mask.png"
    },
    {
        "id": "6643b109558a239478145f25",
        "title": "Rosetta Stone (Replica)",
        "dynasty": "Ptolemaic Era",
        "material": "Granodiorite",
        "site": "Unknown",
        "gallery": "Greco-Roman Period Hall",
        "description": "The key to deciphering ancient Egyptian hieroglyphs. This high-fidelity replica represents the original stele inscribed with a decree in three scripts: Hieroglyphic, Demotic, and Ancient Greek, which allowed scholars to finally unlock the secrets of the Pharaohs.",
        "date": "",
        "image": "../Halls Gallery/images/rosetta_stone.png"
    },
    {
        "id": "6643b109558a239478145f26",
        "title": "Fayum Mummy Portrait",
        "dynasty": "Roman Era",
        "material": "Encaustic on Wood",
        "site": "Unknown",
        "gallery": "Greco-Roman Period Hall",
        "description": "These encaustic-on-wood paintings represent a unique cultural crossroads. While the subjects were mummified in the Egyptian tradition, their portraits were painted in a realistic Roman style, providing the most vivid glimpses we have of the people who lived 2,000 years ago.",
        "date": "",
        "image": "../Halls Gallery/images/fayum_portrait.png"
    },
    {
        "id": "6643b109558a239478145f27",
        "title": "Statue of Sarapis",
        "dynasty": "Ptolemaic Era",
        "material": "Marble",
        "site": "Unknown",
        "gallery": "Greco-Roman Period Hall",
        "description": "Sarapis was a synthetic deity created by Ptolemy I to unite his Greek and Egyptian subjects. This statue combines the physical appearance of the Greek Zeus with the spiritual attributes of the Egyptian Osiris and Apis, symbolizing the multicultural peak of the era.",
        "date": "",
        "image": "../Halls Gallery/images/sarapis_statue.png"
    },
    {
        "id": "6643b109558a239478145f28",
        "title": "Bust of Alexander the Great",
        "dynasty": "Early Ptolemaic",
        "material": "Marble",
        "site": "Unknown",
        "gallery": "Greco-Roman Period Hall",
        "description": "A marble portrait of the Macedonian conqueror who founded Alexandria and was crowned Pharaoh. It captures his characteristic 'anastole' (upward-sweeping hair) and intense gaze, marking the beginning of a new chapter in Egyptian history.",
        "date": "",
        "image": "../Halls Gallery/images/alexander_bust.png"
    }
];