const MAP_DATA = {
    halls: [
        {
            id: "grand-hall",
            name: "Grand Hall",
            nameAr: "البهو العظيم",
            level: "L2",
            description: "The majestic entrance atrium dominated by the colossal 82-ton statue of Ramses II, welcoming visitors with ancient grandeur.",
            descriptionAr: "بهو المدخل المهيب الذي يتوسطه تمثال رمسيس الثاني الضخم، يرحب بالزوار بعظمة التاريخ القديم.",
            artifacts: ["Colossal Ramses II", "Victory Stele of Merneptah", "Ptolemaic Royal Statues"],
            time: "20 mins",
            timeAr: "20 دقيقة",
            image: "../statue-of-ramesses-ii-in-the-entrance-hall-of-the-grand-egyptian-museum-3BNPFMK.jpg",
            category: "statues",
            coordinates: { x: 500, y: 650 },
            nearby: ["hanging-obelisk", "grand-staircase", "commercial-area"],
            connections: ["hanging-obelisk", "grand-staircase", "commercial-area", "childrens-museum"]
        },
        {
            id: "hanging-obelisk",
            name: "Hanging Obelisk Area",
            nameAr: "منطقة المسلة المعلقة",
            level: "L2",
            description: "The world's first hanging obelisk, allowing visitors to see the rare cartouche of Ramses II on its base.",
            descriptionAr: "أول مسلة معلقة في العالم، تتيح للزوار رؤية خرطوشة رمسيس الثاني النادرة على قاعدتها.",
            artifacts: ["Ramses II Obelisk"],
            time: "10 mins",
            timeAr: "10 دقائق",
            image: "../the-entrance-to-the-grand-egyptian-museum-3BAN3ER.jpg",
            category: "pharaohs",
            coordinates: { x: 500, y: 750 },
            nearby: ["grand-hall"],
            connections: ["grand-hall"]
        },
        {
            id: "grand-staircase",
            name: "Grand Staircase",
            nameAr: "الدرج العظيم",
            level: "L2",
            description: "A chronological journey through 87 colossal statues and architectural elements spanning thousands of years of history.",
            descriptionAr: "رحلة تاريخية عبر 87 تمثالاً ضخماً وعناصر معمارية تمتد لآلاف السنين من التاريخ.",
            artifacts: ["Statues of Akhenaten", "Middle Kingdom Sarcophagi", "Old Kingdom Columns"],
            time: "45 mins",
            timeAr: "45 دقيقة",
            image: "../Grand_Staircase_(GEM).jpg",
            category: "statues",
            coordinates: { x: 500, y: 450 },
            nearby: ["grand-hall", "tut-galleries", "main-galleries"],
            connections: ["grand-hall", "tut-galleries", "main-galleries"]
        },
        {
            id: "tut-galleries",
            name: "Tutankhamun Galleries",
            nameAr: "قاعات توت عنخ آمون",
            level: "L3",
            description: "The complete, world-famous collection of the boy king, featuring the golden mask, throne, and over 5,000 artifacts.",
            descriptionAr: "المجموعة الكاملة للملك الشاب، وتضم القناع الذهبي والعرش وأكثر من 5000 قطعة أثرية.",
            artifacts: ["Golden Death Mask", "Golden Throne", "Anubis Shrine"],
            time: "120 mins",
            timeAr: "120 دقيقة",
            image: "../tut-mask.png",
            category: "jewelry",
            coordinates: { x: 300, y: 250 },
            nearby: ["grand-staircase", "main-galleries"],
            connections: ["grand-staircase", "main-galleries"]
        },
        {
            id: "main-galleries",
            name: "Main Galleries",
            nameAr: "القاعات الرئيسية",
            level: "L3",
            description: "A massive exhibition space divided by eras, from the Predynastic period to the Greco-Roman era.",
            descriptionAr: "مساحة عرض ضخمة مقسمة حسب العصور، من عصر ما قبل الأسرات إلى العصر اليوناني الروماني.",
            artifacts: ["Rosetta Stone Replica", "Seated Scribe", "Rahotep and Nofret"],
            time: "180 mins",
            timeAr: "180 دقيقة",
            image: "../hall.jpg",
            category: "pharaohs",
            coordinates: { x: 700, y: 250 },
            nearby: ["grand-staircase", "tut-galleries", "khufu-boats"],
            connections: ["grand-staircase", "tut-galleries", "khufu-boats"]
        },
        {
            id: "childrens-museum",
            name: "Children's Museum",
            nameAr: "متحف الطفل",
            level: "L1",
            description: "An interactive, educational space designed to introduce the youngest visitors to the wonders of Ancient Egypt.",
            descriptionAr: "مساحة تعليمية تفاعلية مصممة لتعريف الزوار الصغار بعجائب مصر القديمة.",
            artifacts: ["Interactive Mummy Puzzle", "Ancient Games Replicas"],
            time: "60 mins",
            timeAr: "60 دقيقة",
            image: "../kids.png",
            category: "pharaohs",
            coordinates: { x: 200, y: 650 },
            nearby: ["grand-hall", "commercial-area"],
            connections: ["grand-hall", "commercial-area"]
        },
        {
            id: "khufu-boats",
            name: "Khufu Boats Museum",
            level: "L3",
            description: "Home to the magnificent solar barks of King Khufu, masterfully preserved for over 4,500 years.",
            artifacts: ["First Solar Bark", "Second Solar Bark"],
            time: "45 mins",
            image: "../the-grand-egyptian-museum-fully-opens-completing-gizas-new-cultural-landmark_7.jpg",
            category: "pharaohs",
            coordinates: { x: 700, y: 100 },
            nearby: ["main-galleries"],
            connections: ["main-galleries"]
        },
        {
            id: "commercial-area",
            name: "Commercial Area",
            level: "L1",
            description: "Premium shopping and dining experience featuring Egyptian-inspired boutiques and world-class restaurants.",
            artifacts: ["Luxury Gift Shops", "Gourmet Cafes"],
            time: "Anytime",
            image: "../the-grand-egyptian-museum-fully-opens-completing-gizas-new-cultural-landmark_8.jpg",
            category: "all",
            coordinates: { x: 800, y: 650 },
            nearby: ["grand-hall", "childrens-museum"],
            connections: ["grand-hall", "childrens-museum"]
        },
        {
            id: "conservation-center",
            name: "Conservation Center",
            level: "L1",
            description: "One of the world's largest and most advanced laboratories for the restoration of ancient antiquities.",
            artifacts: ["State-of-the-art Labs", "Restoration Workshops"],
            time: "Private Tours",
            image: "../tutora-lab.png",
            category: "all",
            coordinates: { x: 150, y: 350 },
            nearby: ["tut-galleries"],
            connections: ["tut-galleries"]
        },
        {
            id: "greco-roman",
            name: "Greco-Roman Period",
            level: "L3",
            description: "The fascinating blend of Ancient Egyptian and Greco-Roman cultures.",
            artifacts: ["Fayum Mummy Portraits"],
            time: "30 mins",
            image: "../hall.jpg",
            category: "greco",
            coordinates: { x: 300, y: 350 },
            nearby: ["tut-galleries"],
            connections: ["tut-galleries"]
        }
    ],
    complex: [
        { id: "main-building", name: "Main Building", nameAr: "المبنى الرئيسي", type: "building", description: "The architectural centerpiece of the GEM, designed by Heneghan Peng Architects. It houses over 100,000 ancient artifacts, including the complete Tutankhamun collection, spread across sweeping galleries.", descriptionAr: "التحفة المعمارية الأساسية للمتحف المصري الكبير، صُممت بواسطة هينيغان بينغ. تضم أكثر من ١٠٠ ألف قطعة أثرية، بما في ذلك مجموعة توت عنخ آمون الكاملة، موزعة عبر قاعات عرض شاسعة.", image: "../hall.jpg", coordinates: { x: 500, y: 450 } },
        { id: "hanging-obelisk-ext", name: "Hanging Obelisk", nameAr: "المسلة المعلقة", type: "poi", labelId: 1, description: "The world's first hanging obelisk, an ingenious engineering marvel at the museum's main entrance. It allows visitors to stand underneath and view the hidden cartouche of King Ramses II carved on its base.", descriptionAr: "أول مسلة معلقة في العالم، معجزة هندسية فريدة في المدخل الرئيسي للمتحف. تتيح للزوار الوقوف تحتها ورؤية الخرطوشة المخفية للملك رمسيس الثاني المنحوتة على قاعدتها.", image: "../gem_hanging_obelisk.png", coordinates: { x: 400, y: 700 } },
        { id: "events-area", name: "Events Area", nameAr: "منطقة الفعاليات", type: "area", labelId: 2, description: "A sprawling outdoor commercial and cultural hub, featuring restaurants, cafes, and open-air venues designed to host international events with a breathtaking backdrop of the Giza Pyramids.", descriptionAr: "منطقة تجارية وثقافية خارجية شاسعة، تضم مطاعم ومقاهي وساحات مفتوحة مصممة لاستضافة الفعاليات الدولية مع خلفية تحبس الأنفاس لأهرامات الجيزة.", image: "../gem_events_area.png", coordinates: { x: 750, y: 650 } },
        { id: "khufu-boats-ext", name: "Khufu's Boats Museum", nameAr: "متحف مراكب خوفو", type: "building", labelId: 3, description: "A state-of-the-art facility specially constructed to house the restored 4,600-year-old solar boat of King Khufu, seamlessly connecting the ancient wooden masterpiece with modern museum technology.", descriptionAr: "مبنى حديث متطور تم إنشاؤه خصيصاً لاحتضان مركب الشمس المستعاد للملك خوفو والذي يعود تاريخه إلى 4600 عام، ليربط بين التحفة الخشبية القديمة وتكنولوجيا المتاحف الحديثة.", image: "../gem_khufu_boats.png", coordinates: { x: 650, y: 400 } },
        { id: "pyramid-steps", name: "Pyramid Steps", nameAr: "سلالم الأهرامات", type: "poi", labelId: 4, description: "The monumental Grand Staircase acts as a vertical gallery, rising 64 meters. It showcases over 60 colossal statues of pharaohs and gods, culminating in a panoramic glass wall facing the Pyramids.", descriptionAr: "الدرج العظيم الأثري الذي يعمل كمعرض عمودي بارتفاع 64 متراً. يعرض أكثر من 60 تمثالاً ضخماً للفراعنة والآلهة، ويتوج بجدار زجاجي بانورامي يطل مباشرة على الأهرامات.", image: "../gem_pyramids_steps.png", coordinates: { x: 400, y: 350 } },
        { id: "conservation-centre-ext", name: "Conservation Centre", nameAr: "مركز الترميم", type: "building", labelId: 5, description: "The largest archaeological conservation center in the Middle East. It features highly advanced laboratories where experts meticulously study, restore, and preserve thousands of artifacts before they are displayed.", descriptionAr: "أكبر مركز للترميم الأثري في الشرق الأوسط. يضم مختبرات متقدمة جداً حيث يقوم الخبراء بدراسة وترميم والحفاظ على آلاف القطع الأثرية بعناية فائقة قبل عرضها.", image: "../gem_conservation_centre.png", coordinates: { x: 500, y: 150 } },
        { id: "sculpture-garden", name: "Sculpture Garden", nameAr: "حديقة المنحوتات", type: "garden", description: "An expansive outdoor gallery blending landscaping with history, featuring selected monumental statues and artifacts strategically placed among greenery, creating a peaceful prelude to the museum.", descriptionAr: "معرض خارجي واسع يمزج بين المناظر الطبيعية والتاريخ، يضم تماثيل ضخمة وقطعاً أثرية مختارة موضوعة استراتيجياً وسط المساحات الخضراء، مما يخلق مقدمة هادئة للمتحف.", image: "../gem_garden.png", coordinates: { x: 250, y: 650 } },
        { id: "terraced-garden", name: "Terraced Garden", nameAr: "الحديقة المدرجة", type: "garden", description: "Beautifully designed stepped landscapes that mimic the Nile Valley's topography. These cascading gardens offer shaded walkways, seating areas, and a seamless transition from the desert plateau.", descriptionAr: "مساحات طبيعية متدرجة مصممة ببراعة لتحاكي تضاريس وادي النيل. توفر هذه الحدائق المتتالية ممرات مظللة ومناطق جلوس وانتقالاً سلساً من الهضبة الصحراوية.", image: "../gem_garden.png", coordinates: { x: 550, y: 350 } },
        { id: "palm-garden", name: "Palm Garden", nameAr: "حديقة النخيل", type: "garden", description: "A serene botanical area reflecting ancient Egyptian agriculture, featuring lush palm groves that provide natural shade and celebrate the flora historically vital to the civilization of the Nile.", descriptionAr: "منطقة نباتية هادئة تعكس الزراعة المصرية القديمة، تتميز ببساتين النخيل المورقة التي توفر ظلاً طبيعياً وتحتفي بالنباتات التي كانت حيوية تاريخياً لحضارة النيل.", image: "../gem_garden.png", coordinates: { x: 700, y: 750 } },
        { id: "parking-main", name: "Main Parking", nameAr: "موقف السيارات الرئيسي", type: "parking", description: "A spacious, modern parking facility accommodating thousands of vehicles and tourist buses, equipped with smart guidance systems and solar-shaded spots for optimal visitor convenience.", descriptionAr: "مرفق سيارات حديث وواسع يستوعب آلاف السيارات وحافلات السياح، مجهز بأنظمة توجيه ذكية ومواقف مظللة بالطاقة الشمسية لراحة الزوار القصوى.", image: "../gem_parking.png", coordinates: { x: 150, y: 800 } },
        { id: "ticketing-entrance", name: "Ticketing & Entrance", nameAr: "مكتب التذاكر والمدخل", type: "building", description: "The majestic welcoming pavilion of the GEM, featuring a streamlined ticketing process, visitor services, and introductory exhibits, setting a grand tone for the journey into ancient history.", descriptionAr: "جناح الاستقبال المهيب للمتحف، يتميز بعملية حجز تذاكر سلسة، وخدمات الزوار، ومعروضات تمهيدية، مما يضفي طابعاً فخماً لرحلة الدخول إلى التاريخ القديم.", image: "../gem_ticketing.png", coordinates: { x: 260, y: 780 } }
    ],
    pois: [
        { id: "wc-1", type: "restroom", name: "Restrooms", coordinates: { x: 250, y: 720 } },
        { id: "wc-2", type: "restroom", name: "Restrooms", coordinates: { x: 750, y: 720 } },
        { id: "lift-1", type: "elevator", name: "Elevators", coordinates: { x: 420, y: 450 } },
        { id: "lift-2", type: "elevator", name: "Elevators", coordinates: { x: 580, y: 450 } },
        { id: "cafe-1", type: "restaurant", name: "Lotus Cafe", coordinates: { x: 850, y: 600 } },
        { id: "shop-1", type: "giftshop", name: "Museum Shop", coordinates: { x: 150, y: 600 } }
    ],
    timeline: [
        { year: "-3100 BC", event: "Unification of Upper and Lower Egypt by King Narmer." },
        { year: "-2580 BC", event: "Construction of the Great Pyramid of Giza by King Khufu." },
        { year: "-1332 BC", event: "Accession of King Tutankhamun to the throne." },
        { year: "-1279 BC", event: "Reign of Ramses II the Great begins." },
        { year: "-30 BC", event: "Death of Cleopatra VII and end of Ptolemaic period." },
        { year: "1922 AD", event: "Discovery of Tutankhamun's tomb by Howard Carter." },
        { year: "2024 AD", event: "Grand opening of the Grand Egyptian Museum." }
    ]
};
