const MAP_DATA = {
    halls: [
        {
            id: "grand-hall",
            name: "Grand Hall",
            nameAr: "البهو العظيم",
            level: "L2",
            description: "The majestic entrance atrium dominated by the colossal 82-ton statue of Ramses II, welcoming visitors with ancient grandeur.",
            descriptionAr: "بهو المدخل المهيب الذي يتوسطه تمثال رمسيس الثاني الضخم، يرحب بالزوار بعظمة التاريخ القديم.",
            artifacts: ["Colossal Ramses II", "Victory Stele of Merneptah", "Ptolemaic Royal Statues"],
            time: "20 mins",
            timeAr: "20 دقيقة",
            image: "../statue-of-ramesses-ii-in-the-entrance-hall-of-the-grand-egyptian-museum-3BNPFMK.jpg",
            category: "statues",
            coordinates: { x: 500, y: 650 },
            nearby: ["hanging-obelisk", "grand-staircase", "commercial-area"],
            connections: ["hanging-obelisk", "grand-staircase", "commercial-area", "childrens-museum"]
        },
        {
            id: "hanging-obelisk",
            name: "Hanging Obelisk Area",
            nameAr: "منطقة المسلة المعلقة",
            level: "L2",
            description: "The world's first hanging obelisk, allowing visitors to see the rare cartouche of Ramses II on its base.",
            descriptionAr: "أول مسلة معلقة في العالم، تتيح للزوار رؤية خرطوشة رمسيس الثاني النادرة على قاعدتها.",
            artifacts: ["Ramses II Obelisk"],
            time: "10 mins",
            timeAr: "10 دقائق",
            image: "../the-entrance-to-the-grand-egyptian-museum-3BAN3ER.jpg",
            category: "pharaohs",
            coordinates: { x: 500, y: 750 },
            nearby: ["grand-hall"],
            connections: ["grand-hall"]
        },
        {
            id: "grand-staircase",
            name: "Grand Staircase",
            nameAr: "الدرج العظيم",
            level: "L2",
            description: "A chronological journey through 87 colossal statues and architectural elements spanning thousands of years of history.",
            descriptionAr: "رحلة تاريخية عبر 87 تمثالاً ضخماً وعناصر معمارية تمتد لآلاف السنين من التاريخ.",
            artifacts: ["Statues of Akhenaten", "Middle Kingdom Sarcophagi", "Old Kingdom Columns"],
            time: "45 mins",
            timeAr: "45 دقيقة",
            image: "../Grand_Staircase_(GEM).jpg",
            category: "statues",
            coordinates: { x: 500, y: 450 },
            nearby: ["grand-hall", "tut-galleries", "main-galleries"],
            connections: ["grand-hall", "tut-galleries", "main-galleries"]
        },
        {
            id: "tut-galleries",
            name: "Tutankhamun Galleries",
            nameAr: "قاعات توت عنخ آمون",
            level: "L3",
            description: "The complete, world-famous collection of the boy king, featuring the golden mask, throne, and over 5,000 artifacts.",
            descriptionAr: "المجموعة الكاملة للملك الشاب، وتضم القناع الذهبي والعرش وأكثر من 5000 قطعة أثرية.",
            artifacts: ["Golden Death Mask", "Golden Throne", "Anubis Shrine"],
            time: "120 mins",
            timeAr: "120 دقيقة",
            image: "../tut-mask.png",
            category: "jewelry",
            coordinates: { x: 300, y: 250 },
            nearby: ["grand-staircase", "main-galleries"],
            connections: ["grand-staircase", "main-galleries"]
        },
        {
            id: "main-galleries",
            name: "Main Galleries",
            nameAr: "القاعات الرئيسية",
            level: "L3",
            description: "A massive exhibition space divided by eras, from the Predynastic period to the Greco-Roman era.",
            descriptionAr: "مساحة عرض ضخمة مقسمة حسب العصور، من عصر ما قبل الأسرات إلى العصر اليوناني الروماني.",
            artifacts: ["Rosetta Stone Replica", "Seated Scribe", "Rahotep and Nofret"],
            time: "180 mins",
            timeAr: "180 دقيقة",
            image: "../hall.jpg",
            category: "pharaohs",
            coordinates: { x: 700, y: 250 },
            nearby: ["grand-staircase", "tut-galleries", "khufu-boats"],
            connections: ["grand-staircase", "tut-galleries", "khufu-boats"]
        },
        {
            id: "childrens-museum",
            name: "Children's Museum",
            nameAr: "متحف الطفل",
            level: "L1",
            description: "An interactive, educational space designed to introduce the youngest visitors to the wonders of Ancient Egypt.",
            descriptionAr: "مساحة تعليمية تفاعلية مصممة لتعريف الزوار الصغار بعجائب مصر القديمة.",
            artifacts: ["Interactive Mummy Puzzle", "Ancient Games Replicas"],
            time: "60 mins",
            timeAr: "60 دقيقة",
            image: "../kids.png",
            category: "pharaohs",
            coordinates: { x: 200, y: 650 },
            nearby: ["grand-hall", "commercial-area"],
            connections: ["grand-hall", "commercial-area"]
        },
        {
            id: "khufu-boats",
            name: "Khufu Boats Museum",
            level: "L3",
            description: "Home to the magnificent solar barks of King Khufu, masterfully preserved for over 4,500 years.",
            artifacts: ["First Solar Bark", "Second Solar Bark"],
            time: "45 mins",
            image: "../the-grand-egyptian-museum-fully-opens-completing-gizas-new-cultural-landmark_7.jpg",
            category: "pharaohs",
            coordinates: { x: 700, y: 100 },
            nearby: ["main-galleries"],
            connections: ["main-galleries"]
        },
        {
            id: "commercial-area",
            name: "Commercial Area",
            level: "L1",
            description: "Premium shopping and dining experience featuring Egyptian-inspired boutiques and world-class restaurants.",
            artifacts: ["Luxury Gift Shops", "Gourmet Cafes"],
            time: "Anytime",
            image: "../the-grand-egyptian-museum-fully-opens-completing-gizas-new-cultural-landmark_8.jpg",
            category: "all",
            coordinates: { x: 800, y: 650 },
            nearby: ["grand-hall", "childrens-museum"],
            connections: ["grand-hall", "childrens-museum"]
        },
        {
            id: "conservation-center",
            name: "Conservation Center",
            level: "L1",
            description: "One of the world's largest and most advanced laboratories for the restoration of ancient antiquities.",
            artifacts: ["State-of-the-art Labs", "Restoration Workshops"],
            time: "Private Tours",
            image: "../tutora-lab.png",
            category: "all",
            coordinates: { x: 150, y: 350 },
            nearby: ["tut-galleries"],
            connections: ["tut-galleries"]
        },
        {
            id: "greco-roman",
            name: "Greco-Roman Period",
            level: "L3",
            description: "The fascinating blend of Ancient Egyptian and Greco-Roman cultures.",
            artifacts: ["Fayum Mummy Portraits"],
            time: "30 mins",
            image: "../hall.jpg",
            category: "greco",
            coordinates: { x: 300, y: 350 },
            nearby: ["tut-galleries"],
            connections: ["tut-galleries"]
        }
    ],
    complex: [
        { id: "main-building", name: "Main Building", nameAr: "المبنى الرئيسي", type: "building", description: "The architectural centerpiece of the GEM, designed by Heneghan Peng Architects. This monumental structure houses over 100,000 ancient artifacts, spanning from pre-dynastic times to the Greco-Roman period. It is distinguished by its translucent alabaster facade and sweeping galleries, offering the most comprehensive collection of Egyptian antiquities in the world.<br><br><strong style='color:#d4af37;'>Location:</strong> Central Museum Structure, accessible directly from the main entrance plaza.", descriptionAr: "التحفة المعمارية الأساسية للمتحف المصري الكبير. يضم هذا المبنى الضخم أكثر من 100 ألف قطعة أثرية، تمتد من عصور ما قبل الأسرات وحتى العصر اليوناني الروماني. يتميز بواجهته الشفافة من المرمر وقاعات العرض الشاسعة، ليقدم أشمل مجموعة من الآثار المصرية في العالم.<br><br><strong style='color:#d4af37;'>الموقع:</strong> هيكل المتحف المركزي، ويمكن الوصول إليه مباشرة من ساحة المدخل الرئيسية.", image: "../hall.jpg", coordinates: { x: 500, y: 450 } },
        { id: "hanging-obelisk-ext", name: "Hanging Obelisk", nameAr: "المسلة المعلقة", type: "poi", labelId: 1, description: "The world's first hanging obelisk, an ingenious engineering marvel greeting visitors at the museum's main entrance. By suspending the ancient 3,000-year-old obelisk of King Ramses II on a modern architectural base, it allows visitors an unprecedented experience: standing underneath it to view the hidden royal cartouche carved on its base.<br><br><strong style='color:#d4af37;'>Location:</strong> The Main Entrance Plaza, immediately outside the ticketing pavilion.", descriptionAr: "أول مسلة معلقة في العالم، معجزة هندسية فريدة تستقبل الزوار في المدخل الرئيسي للمتحف. من خلال تعليق مسلة الملك رمسيس الثاني التي يبلغ عمرها 3000 عام على قاعدة معمارية حديثة، تمنح الزوار تجربة غير مسبوقة للوقوف تحتها ورؤية الخرطوشة الملكية المخفية المنحوتة على قاعدتها.<br><br><strong style='color:#d4af37;'>الموقع:</strong> ساحة المدخل الرئيسية، خارج مبنى التذاكر مباشرة.", image: "../gem_hanging_obelisk.png", coordinates: { x: 400, y: 700 } },
        { id: "events-area", name: "Events Area", nameAr: "منطقة الفعاليات", type: "area", labelId: 2, description: "A sprawling outdoor commercial and cultural hub spanning thousands of square meters. It features a diverse range of high-end restaurants, cafes, and open-air venues designed to host local and international events. Visitors can enjoy their time here with a breathtaking, unobstructed backdrop of the iconic Giza Pyramids.<br><br><strong style='color:#d4af37;'>Location:</strong> The Eastern Commercial Plaza, connecting the main entrance to the gardens.", descriptionAr: "منطقة تجارية وثقافية خارجية شاسعة تمتد على مساحة آلاف الأمتار المربعة. تضم مجموعة متنوعة من المطاعم الراقية، والمقاهي، والساحات المفتوحة المصممة لاستضافة الفعاليات المحلية والدولية مع خلفية تحبس الأنفاس لأهرامات الجيزة الأيقونية.<br><br><strong style='color:#d4af37;'>الموقع:</strong> الساحة التجارية الشرقية، تربط المدخل الرئيسي بالحدائق.", image: "../gem_events_area.png", coordinates: { x: 750, y: 650 } },
        { id: "khufu-boats-ext", name: "Khufu's Boats Museum", nameAr: "متحف مراكب خوفو", type: "building", labelId: 3, description: "A state-of-the-art facility specially constructed to house the meticulously restored 4,600-year-old solar boat of King Khufu. The building's climate-controlled environment and immersive displays seamlessly connect the ancient wooden masterpiece with modern museum technology, ensuring its preservation for future generations.<br><br><strong style='color:#d4af37;'>Location:</strong> Dedicated building directly adjacent to the western side of the Main Building.", descriptionAr: "مبنى حديث ومتطور تم إنشاؤه خصيصاً لاحتضان مركب الشمس المستعاد للملك خوفو والذي يعود تاريخه إلى 4600 عام. البيئة التي يتم التحكم في مناخها داخل المبنى وعروضه الغامرة تربط بسلاسة بين التحفة الخشبية القديمة وتكنولوجيا المتاحف الحديثة.<br><br><strong style='color:#d4af37;'>الموقع:</strong> مبنى مخصص مجاور مباشرة للجانب الغربي من المبنى الرئيسي.", image: "../gem_khufu_boats.png", coordinates: { x: 650, y: 400 } },
        { id: "pyramid-steps", name: "Pyramid Steps", nameAr: "سلالم الأهرامات", type: "poi", labelId: 4, description: "The monumental Grand Staircase acts as a vertical gallery, rising 64 meters along the museum's axis. It beautifully showcases over 60 colossal statues of pharaohs and gods, chronologically arranged. The ascent culminates at the top in a panoramic glass wall that perfectly frames the Great Pyramids.<br><br><strong style='color:#d4af37;'>Location:</strong> Inside the Main Building, serving as the main spine connecting the entrance atrium to the upper galleries.", descriptionAr: "الدرج العظيم الأثري الذي يعمل كمعرض عمودي يرتفع لمسافة 64 متراً على طول محور المتحف. يعرض بشكل رائع أكثر من 60 تمثالاً ضخماً للفراعنة والآلهة. يتوج الصعود في الأعلى بجدار زجاجي بانورامي يؤطر الأهرامات العظيمة بشكل مثالي.<br><br><strong style='color:#d4af37;'>الموقع:</strong> داخل المبنى الرئيسي، ويعمل كالمحور الأساسي الذي يربط بهو المدخل بالقاعات العلوية.", image: "../gem_pyramids_steps.png", coordinates: { x: 400, y: 350 } },
        { id: "conservation-centre-ext", name: "Conservation Centre", nameAr: "مركز الترميم", type: "building", labelId: 5, description: "The largest archaeological conservation center in the Middle East. It features highly advanced, specialized laboratories for wood, stone, and organic materials. Here, world-class experts meticulously study, restore, and preserve thousands of artifacts before they are safely moved to the display areas.<br><br><strong style='color:#d4af37;'>Location:</strong> Independent facility located in the northern sector of the museum complex.", descriptionAr: "أكبر مركز للترميم الأثري في الشرق الأوسط. يضم مختبرات متقدمة ومتخصصة جداً للأخشاب والأحجار والمواد العضوية. هنا، يقوم الخبراء العالميون بدراسة وترميم والحفاظ على آلاف القطع الأثرية بعناية فائقة قبل نقلها بأمان إلى مناطق العرض.<br><br><strong style='color:#d4af37;'>الموقع:</strong> مرفق مستقل يقع في القطاع الشمالي من مجمع المتحف.", image: "../gem_conservation_centre.png", coordinates: { x: 500, y: 150 } },
        { id: "sculpture-garden", name: "Sculpture Garden", nameAr: "حديقة المنحوتات", type: "garden", description: "An expansive outdoor gallery blending serene landscaping with history. This garden features carefully selected monumental statues and large stone artifacts strategically placed among lush greenery, creating a peaceful and inspiring prelude to the museum's indoor collections.<br><br><strong style='color:#d4af37;'>Location:</strong> The Southern Outdoor Area, flanking the main approach to the museum.", descriptionAr: "معرض خارجي واسع يمزج بين المناظر الطبيعية الهادئة والتاريخ. تضم هذه الحديقة تماثيل ضخمة مختارة بعناية وقطعاً أثرية حجرية كبيرة موضوعة استراتيجياً وسط المساحات الخضراء، مما يخلق مقدمة هادئة وملهمة لمجموعات المتحف الداخلية.<br><br><strong style='color:#d4af37;'>الموقع:</strong> المنطقة الخارجية الجنوبية، على جانبي الطريق المؤدي للمتحف.", image: "../gem_garden.png", coordinates: { x: 250, y: 650 } },
        { id: "terraced-garden", name: "Terraced Garden", nameAr: "الحديقة المدرجة", type: "garden", description: "Beautifully designed stepped landscapes that intricately mimic the natural topography of the Nile Valley. These cascading gardens offer visitors shaded walkways, comfortable seating areas, and a seamless visual and physical transition from the arid desert plateau to the green valley.<br><br><strong style='color:#d4af37;'>Location:</strong> Sloping terrain on the eastern edge, connecting the lower parking to the upper entrance.", descriptionAr: "مساحات طبيعية متدرجة مصممة ببراعة لتحاكي الطبيعة الطبوغرافية لوادي النيل. توفر هذه الحدائق المتتالية للزوار ممرات مظللة، ومناطق جلوس مريحة، وانتقالاً بصرياً ومادياً سلساً من الهضبة الصحراوية القاحلة إلى الوادي الأخضر.<br><br><strong style='color:#d4af37;'>الموقع:</strong> التضاريس المنحدرة على الحافة الشرقية، تربط مواقف السيارات السفلية بالمدخل العلوي.", image: "../gem_garden.png", coordinates: { x: 550, y: 350 } },
        { id: "palm-garden", name: "Palm Garden", nameAr: "حديقة النخيل", type: "garden", description: "A serene botanical area reflecting ancient Egyptian agriculture. It features lush, organized palm groves that provide generous natural shade. The garden serves to celebrate the flora that was historically vital to the life and civilization of the Nile valley inhabitants.<br><br><strong style='color:#d4af37;'>Location:</strong> Western gardens zone, near the Khufu Boats Museum.", descriptionAr: "منطقة نباتية هادئة تعكس الزراعة المصرية القديمة. تتميز ببساتين النخيل المورقة والمنظمة التي توفر ظلاً طبيعياً وفيراً. تهدف الحديقة للاحتفاء بالنباتات التي كانت حيوية تاريخياً لحياة وحضارة سكان وادي النيل.<br><br><strong style='color:#d4af37;'>الموقع:</strong> منطقة الحدائق الغربية، بالقرب من متحف مراكب خوفو.", image: "../gem_garden.png", coordinates: { x: 700, y: 750 } },
        { id: "parking-main", name: "Main Parking", nameAr: "موقف السيارات الرئيسي", type: "parking", description: "A remarkably spacious, highly modern parking facility designed to comfortably accommodate thousands of visitor vehicles and tourist buses. It is fully equipped with smart parking guidance systems and eco-friendly solar-shaded spots, ensuring optimal convenience and sustainability.<br><br><strong style='color:#d4af37;'>Location:</strong> The outermost perimeter on the eastern side, accessible directly from the Cairo-Alexandria desert road.", descriptionAr: "مرفق سيارات حديث وواسع بشكل ملحوظ، مصمم لاستيعاب آلاف سيارات الزوار وحافلات السياح براحة تامة. مجهز بالكامل بأنظمة توجيه ذكية لمواقف السيارات ومواقف مظللة بالطاقة الشمسية صديقة للبيئة، مما يضمن أقصى درجات الراحة والاستدامة.<br><br><strong style='color:#d4af37;'>الموقع:</strong> المحيط الخارجي على الجانب الشرقي، ويمكن الوصول إليه مباشرة من طريق القاهرة-الإسكندرية الصحراوي.", image: "../gem_parking.png", coordinates: { x: 150, y: 800 } },
        { id: "ticketing-entrance", name: "Ticketing & Entrance", nameAr: "مكتب التذاكر والمدخل", type: "building", description: "The majestic welcoming pavilion of the GEM. It features a highly streamlined digital ticketing process, comprehensive visitor services, and captivating introductory exhibits. This area sets a grand, organized tone for the monumental journey into ancient history that awaits inside.<br><br><strong style='color:#d4af37;'>Location:</strong> The primary entrance gate at the eastern front of the complex, leading into the main atrium.", descriptionAr: "جناح الاستقبال المهيب للمتحف. يتميز بعملية حجز تذاكر رقمية سلسة للغاية، وخدمات زوار شاملة، ومعروضات تمهيدية جذابة. تضفي هذه المنطقة طابعاً فخماً ومنظماً للرحلة الأثرية العظيمة في التاريخ القديم التي تنتظر بالداخل.<br><br><strong style='color:#d4af37;'>الموقع:</strong> بوابة الدخول الرئيسية في الواجهة الشرقية للمجمع، والمؤدية إلى البهو الرئيسي.", image: "../gem_ticketing.png", coordinates: { x: 260, y: 780 } }
    ],
    pois: [
        { id: "wc-1", type: "restroom", name: "Restrooms", coordinates: { x: 250, y: 720 } },
        { id: "wc-2", type: "restroom", name: "Restrooms", coordinates: { x: 750, y: 720 } },
        { id: "lift-1", type: "elevator", name: "Elevators", coordinates: { x: 420, y: 450 } },
        { id: "lift-2", type: "elevator", name: "Elevators", coordinates: { x: 580, y: 450 } },
        { id: "cafe-1", type: "restaurant", name: "Lotus Cafe", coordinates: { x: 850, y: 600 } },
        { id: "shop-1", type: "giftshop", name: "Museum Shop", coordinates: { x: 150, y: 600 } }
    ],
    timeline: [
        { year: "-3100 BC", event: "Unification of Upper and Lower Egypt by King Narmer." },
        { year: "-2580 BC", event: "Construction of the Great Pyramid of Giza by King Khufu." },
        { year: "-1332 BC", event: "Accession of King Tutankhamun to the throne." },
        { year: "-1279 BC", event: "Reign of Ramses II the Great begins." },
        { year: "-30 BC", event: "Death of Cleopatra VII and end of Ptolemaic period." },
        { year: "1922 AD", event: "Discovery of Tutankhamun's tomb by Howard Carter." },
        { year: "2024 AD", event: "Grand opening of the Grand Egyptian Museum." }
    ]
};
