const MAP_DATA = {
    halls: [
        {
            id: "grand-hall",
            name: "Grand Hall",
            nameAr: "البهو العظيم",
            level: "L2",
            description: "The majestic entrance atrium dominated by the colossal 82-ton statue of Ramses II, welcoming visitors with ancient grandeur.",
            descriptionAr: "بهو المدخل المهيب الذي يتوسطه تمثال رمسيس الثاني الضخم، يرحب بالزوار بعظمة التاريخ القديم.",
            artifacts: ["Colossal Ramses II", "Victory Stele of Merneptah", "Ptolemaic Royal Statues"],
            time: "20 mins",
            timeAr: "20 دقيقة",
            image: "../statue-of-ramesses-ii-in-the-entrance-hall-of-the-grand-egyptian-museum-3BNPFMK.jpg",
            category: "statues",
            coordinates: { x: 500, y: 650 },
            nearby: ["hanging-obelisk", "grand-staircase", "commercial-area"],
            connections: ["hanging-obelisk", "grand-staircase", "commercial-area", "childrens-museum"]
        },
        {
            id: "hanging-obelisk",
            name: "Hanging Obelisk Area",
            nameAr: "منطقة المسلة المعلقة",
            level: "L2",
            description: "The world's first hanging obelisk, allowing visitors to see the rare cartouche of Ramses II on its base.",
            descriptionAr: "أول مسلة معلقة في العالم، تتيح للزوار رؤية خرطوشة رمسيس الثاني النادرة على قاعدتها.",
            artifacts: ["Ramses II Obelisk"],
            time: "10 mins",
            timeAr: "10 دقائق",
            image: "../the-entrance-to-the-grand-egyptian-museum-3BAN3ER.jpg",
            category: "pharaohs",
            coordinates: { x: 500, y: 750 },
            nearby: ["grand-hall"],
            connections: ["grand-hall"]
        },
        {
            id: "grand-staircase",
            name: "Grand Staircase",
            nameAr: "الدرج العظيم",
            level: "L2",
            description: "A chronological journey through 87 colossal statues and architectural elements spanning thousands of years of history.",
            descriptionAr: "رحلة تاريخية عبر 87 تمثالاً ضخماً وعناصر معمارية تمتد لآلاف السنين من التاريخ.",
            artifacts: ["Statues of Akhenaten", "Middle Kingdom Sarcophagi", "Old Kingdom Columns"],
            time: "45 mins",
            timeAr: "45 دقيقة",
            image: "../Grand_Staircase_(GEM).jpg",
            category: "statues",
            coordinates: { x: 500, y: 450 },
            nearby: ["grand-hall", "tut-galleries", "main-galleries"],
            connections: ["grand-hall", "tut-galleries", "main-galleries"]
        },
        {
            id: "tut-galleries",
            name: "Tutankhamun Galleries",
            nameAr: "قاعات توت عنخ آمون",
            level: "L3",
            description: "The complete, world-famous collection of the boy king, featuring the golden mask, throne, and over 5,000 artifacts.",
            descriptionAr: "المجموعة الكاملة للملك الشاب، وتضم القناع الذهبي والعرش وأكثر من 5000 قطعة أثرية.",
            artifacts: ["Golden Death Mask", "Golden Throne", "Anubis Shrine"],
            time: "120 mins",
            timeAr: "120 دقيقة",
            image: "../tut-mask.png",
            category: "jewelry",
            coordinates: { x: 300, y: 250 },
            nearby: ["grand-staircase", "main-galleries"],
            connections: ["grand-staircase", "main-galleries"]
        },
        {
            id: "main-galleries",
            name: "Main Galleries",
            nameAr: "القاعات الرئيسية",
            level: "L3",
            description: "A massive exhibition space divided by eras, from the Predynastic period to the Greco-Roman era.",
            descriptionAr: "مساحة عرض ضخمة مقسمة حسب العصور، من عصر ما قبل الأسرات إلى العصر اليوناني الروماني.",
            artifacts: ["Rosetta Stone Replica", "Seated Scribe", "Rahotep and Nofret"],
            time: "180 mins",
            timeAr: "180 دقيقة",
            image: "../hall.jpg",
            category: "pharaohs",
            coordinates: { x: 700, y: 250 },
            nearby: ["grand-staircase", "tut-galleries", "khufu-boats"],
            connections: ["grand-staircase", "tut-galleries", "khufu-boats"]
        },
        {
            id: "childrens-museum",
            name: "Children's Museum",
            nameAr: "متحف الطفل",
            level: "L1",
            description: "An interactive, educational space designed to introduce the youngest visitors to the wonders of Ancient Egypt.",
            descriptionAr: "مساحة تعليمية تفاعلية مصممة لتعريف الزوار الصغار بعجائب مصر القديمة.",
            artifacts: ["Interactive Mummy Puzzle", "Ancient Games Replicas"],
            time: "60 mins",
            timeAr: "60 دقيقة",
            image: "../kids.png",
            category: "pharaohs",
            coordinates: { x: 200, y: 650 },
            nearby: ["grand-hall", "commercial-area"],
            connections: ["grand-hall", "commercial-area"]
        },
        {
            id: "khufu-boats",
            name: "Khufu Boats Museum",
            level: "L3",
            description: "Home to the magnificent solar barks of King Khufu, masterfully preserved for over 4,500 years.",
            artifacts: ["First Solar Bark", "Second Solar Bark"],
            time: "45 mins",
            image: "../the-grand-egyptian-museum-fully-opens-completing-gizas-new-cultural-landmark_7.jpg",
            category: "pharaohs",
            coordinates: { x: 700, y: 100 },
            nearby: ["main-galleries"],
            connections: ["main-galleries"]
        },
        {
            id: "commercial-area",
            name: "Commercial Area",
            level: "L1",
            description: "Premium shopping and dining experience featuring Egyptian-inspired boutiques and world-class restaurants.",
            artifacts: ["Luxury Gift Shops", "Gourmet Cafes"],
            time: "Anytime",
            image: "../the-grand-egyptian-museum-fully-opens-completing-gizas-new-cultural-landmark_8.jpg",
            category: "all",
            coordinates: { x: 800, y: 650 },
            nearby: ["grand-hall", "childrens-museum"],
            connections: ["grand-hall", "childrens-museum"]
        },
        {
            id: "conservation-center",
            name: "Conservation Center",
            level: "L1",
            description: "One of the world's largest and most advanced laboratories for the restoration of ancient antiquities.",
            artifacts: ["State-of-the-art Labs", "Restoration Workshops"],
            time: "Private Tours",
            image: "../tutora-lab.png",
            category: "all",
            coordinates: { x: 150, y: 350 },
            nearby: ["tut-galleries"],
            connections: ["tut-galleries"]
        },
        {
            id: "greco-roman",
            name: "Greco-Roman Period",
            level: "L3",
            description: "The fascinating blend of Ancient Egyptian and Greco-Roman cultures.",
            artifacts: ["Fayum Mummy Portraits"],
            time: "30 mins",
            image: "../hall.jpg",
            category: "greco",
            coordinates: { x: 300, y: 350 },
            nearby: ["tut-galleries"],
            connections: ["tut-galleries"]
        }
    ],
    complex: [
        { id: "main-building", name: "Main Building", nameAr: "المبنى الرئيسي", type: "building", description: "The architectural centerpiece of the GEM, housing the main galleries and the Grand Staircase.", descriptionAr: "المركز المعماري للمتحف، يضم القاعات الرئيسية والدرج العظيم.", image: "../hall.jpg", coordinates: { x: 500, y: 450 } },
        { id: "hanging-obelisk-ext", name: "Hanging Obelisk", nameAr: "المسلة المعلقة", type: "poi", labelId: 1, description: "The world's first hanging obelisk, showcasing the cartouche of Ramses II on its base.", descriptionAr: "أول مسلة معلقة في العالم، تظهر خرطوشة رمسيس الثاني على قاعدتها.", image: "../gem_hanging_obelisk.png", coordinates: { x: 400, y: 700 } },
        { id: "events-area", name: "Events Area", nameAr: "منطقة الفعاليات", type: "area", labelId: 2, description: "Outdoor venue for cultural events and exhibitions with views of the Giza Pyramids.", descriptionAr: "مكان خارجي للفعاليات الثقافية والمعارض مع إطلالة على أهرامات الجيزة.", image: "../gem_events_area.png", coordinates: { x: 750, y: 650 } },
        { id: "khufu-boats-ext", name: "Khufu's Boats Museum", nameAr: "متحف مراكب خوفو", type: "building", labelId: 3, description: "Dedicated museum for the ancient solar barks of King Khufu.", descriptionAr: "متحف مخصص لمراكب الشمس القديمة للملك خوفو.", image: "../gem_khufu_boats.png", coordinates: { x: 650, y: 400 } },
        { id: "pyramid-steps", name: "Pyramid Steps", nameAr: "سلالم الأهرامات", type: "poi", labelId: 4, description: "A unique architectural viewpoint overlooking the Giza plateau.", descriptionAr: "نقطة مراقبة معمارية فريدة تطل على هضبة الجيزة.", image: "../gem_pyramids_steps.png", coordinates: { x: 400, y: 350 } },
        { id: "conservation-centre-ext", name: "Conservation Centre", nameAr: "مركز الترميم", type: "building", labelId: 5, description: "Advanced laboratories for the restoration and preservation of Egypt's artifacts.", descriptionAr: "مختبرات متقدمة لترميم والحفاظ على آثار مصر.", image: "../gem_conservation_centre.png", coordinates: { x: 500, y: 150 } },
        { id: "sculpture-garden", name: "Sculpture Garden", nameAr: "حديقة المنحوتات", type: "garden", description: "Open-air gallery featuring monumental statues from various eras of Egyptian history.", descriptionAr: "معرض مفتوح يعرض تماثيل ضخمة من عصور مختلفة من التاريخ المصري.", image: "../gem_garden.png", coordinates: { x: 250, y: 650 } },
        { id: "terraced-garden", name: "Terraced Garden", nameAr: "الحديقة المدرجة", type: "garden", description: "Beautifully landscaped gardens offering a peaceful environment for visitors.", descriptionAr: "حدائق ذات مناظر طبيعية جميلة توفر بيئة هادئة للزوار.", image: "../gem_garden.png", coordinates: { x: 550, y: 350 } },
        { id: "palm-garden", name: "Palm Garden", nameAr: "حديقة النخيل", type: "garden", description: "Lush palm groves representing the fertile lands of the Nile valley.", descriptionAr: "بساتين النخيل المورقة تمثل الأراضي الخصبة لوادي النيل.", image: "../gem_garden.png", coordinates: { x: 700, y: 750 } },
        { id: "parking-main", name: "Main Parking", nameAr: "موقف السيارات الرئيسي", type: "parking", description: "Primary visitor parking area with easy access to the ticketing entrance.", descriptionAr: "منطقة مواقف الزوار الرئيسية مع وصول سهل لمدخل التذاكر.", image: "../gem_parking.png", coordinates: { x: 150, y: 800 } },
        { id: "ticketing-entrance", name: "Ticketing & Entrance", nameAr: "مكتب التذاكر والمدخل", type: "building", description: "Main ticketing and visitor entrance area.", descriptionAr: "منطقة التذاكر الرئيسية ومدخل الزوار.", image: "../gem_ticketing.png", coordinates: { x: 260, y: 780 } }
    ],
    pois: [
        { id: "wc-1", type: "restroom", name: "Restrooms", coordinates: { x: 250, y: 720 } },
        { id: "wc-2", type: "restroom", name: "Restrooms", coordinates: { x: 750, y: 720 } },
        { id: "lift-1", type: "elevator", name: "Elevators", coordinates: { x: 420, y: 450 } },
        { id: "lift-2", type: "elevator", name: "Elevators", coordinates: { x: 580, y: 450 } },
        { id: "cafe-1", type: "restaurant", name: "Lotus Cafe", coordinates: { x: 850, y: 600 } },
        { id: "shop-1", type: "giftshop", name: "Museum Shop", coordinates: { x: 150, y: 600 } }
    ],
    timeline: [
        { year: "-3100 BC", event: "Unification of Upper and Lower Egypt by King Narmer." },
        { year: "-2580 BC", event: "Construction of the Great Pyramid of Giza by King Khufu." },
        { year: "-1332 BC", event: "Accession of King Tutankhamun to the throne." },
        { year: "-1279 BC", event: "Reign of Ramses II the Great begins." },
        { year: "-30 BC", event: "Death of Cleopatra VII and end of Ptolemaic period." },
        { year: "1922 AD", event: "Discovery of Tutankhamun's tomb by Howard Carter." },
        { year: "2024 AD", event: "Grand opening of the Grand Egyptian Museum." }
    ]
};
